#Minecraft server properties
#Wed Sep 24 09:10:30 UTC 2025
accepts-transfers=true
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
online-mode=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=40
max-tick-time=60000
max-world-size=3500
motd=\u00a73\u00a7lNanoSMP\u00a7c\u00a7l \u00a7c\u00a7n\u00a7oSurvival SMP\u00a7c \u00a76\u00a7l \u00a7kherobrine
network-compression-threshold=512
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=minecraft
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=4
spawn-monsters=true
spawn-protection=16
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=7
white-list=false